//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 2010.12.29 00:21:07
namespace ODataLambda.Tests.MicrosoftPdcData
{
    
    /// <summary>
    /// There are no comments for ScheduleModel in the schema.
    /// </summary>
    public partial class ScheduleModel : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new ScheduleModel object.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ScheduleModel(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("Shared.Model", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("ODataLambda.Tests.MicrosoftPdcData", typeName.Substring(12)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("ODataLambda.Tests.MicrosoftPdcData", global::System.StringComparison.Ordinal))
            {
                return string.Concat("Shared.Model.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for ScheduleOfEvents in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Schedule> ScheduleOfEvents
        {
            get
            {
                if ((this._ScheduleOfEvents == null))
                {
                    this._ScheduleOfEvents = base.CreateQuery<Schedule>("ScheduleOfEvents");
                }
                return this._ScheduleOfEvents;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Schedule> _ScheduleOfEvents;
        /// <summary>
        /// There are no comments for Sessions in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Session> Sessions
        {
            get
            {
                if ((this._Sessions == null))
                {
                    this._Sessions = base.CreateQuery<Session>("Sessions");
                }
                return this._Sessions;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Session> _Sessions;
        /// <summary>
        /// There are no comments for Tracks in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Track> Tracks
        {
            get
            {
                if ((this._Tracks == null))
                {
                    this._Tracks = base.CreateQuery<Track>("Tracks");
                }
                return this._Tracks;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Track> _Tracks;
        /// <summary>
        /// There are no comments for TimeSlots in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<TimeSlot> TimeSlots
        {
            get
            {
                if ((this._TimeSlots == null))
                {
                    this._TimeSlots = base.CreateQuery<TimeSlot>("TimeSlots");
                }
                return this._TimeSlots;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<TimeSlot> _TimeSlots;
        /// <summary>
        /// There are no comments for Speakers in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Speaker> Speakers
        {
            get
            {
                if ((this._Speakers == null))
                {
                    this._Speakers = base.CreateQuery<Speaker>("Speakers");
                }
                return this._Speakers;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Speaker> _Speakers;
        /// <summary>
        /// There are no comments for Manifests in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Manifest> Manifests
        {
            get
            {
                if ((this._Manifests == null))
                {
                    this._Manifests = base.CreateQuery<Manifest>("Manifests");
                }
                return this._Manifests;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Manifest> _Manifests;
        /// <summary>
        /// There are no comments for Presenters in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Presenter> Presenters
        {
            get
            {
                if ((this._Presenters == null))
                {
                    this._Presenters = base.CreateQuery<Presenter>("Presenters");
                }
                return this._Presenters;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Presenter> _Presenters;
        /// <summary>
        /// There are no comments for Contents in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Content> Contents
        {
            get
            {
                if ((this._Contents == null))
                {
                    this._Contents = base.CreateQuery<Content>("Contents");
                }
                return this._Contents;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Content> _Contents;
        /// <summary>
        /// There are no comments for RelatedSessions in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<RelatedSession> RelatedSessions
        {
            get
            {
                if ((this._RelatedSessions == null))
                {
                    this._RelatedSessions = base.CreateQuery<RelatedSession>("RelatedSessions");
                }
                return this._RelatedSessions;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<RelatedSession> _RelatedSessions;
        /// <summary>
        /// There are no comments for ScheduleOfEvents in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToScheduleOfEvents(Schedule schedule)
        {
            base.AddObject("ScheduleOfEvents", schedule);
        }
        /// <summary>
        /// There are no comments for Sessions in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSessions(Session session)
        {
            base.AddObject("Sessions", session);
        }
        /// <summary>
        /// There are no comments for Tracks in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTracks(Track track)
        {
            base.AddObject("Tracks", track);
        }
        /// <summary>
        /// There are no comments for TimeSlots in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTimeSlots(TimeSlot timeSlot)
        {
            base.AddObject("TimeSlots", timeSlot);
        }
        /// <summary>
        /// There are no comments for Speakers in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSpeakers(Speaker speaker)
        {
            base.AddObject("Speakers", speaker);
        }
        /// <summary>
        /// There are no comments for Manifests in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToManifests(Manifest manifest)
        {
            base.AddObject("Manifests", manifest);
        }
        /// <summary>
        /// There are no comments for Presenters in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToPresenters(Presenter presenter)
        {
            base.AddObject("Presenters", presenter);
        }
        /// <summary>
        /// There are no comments for Contents in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToContents(Content content)
        {
            base.AddObject("Contents", content);
        }
        /// <summary>
        /// There are no comments for RelatedSessions in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToRelatedSessions(RelatedSession relatedSession)
        {
            base.AddObject("RelatedSessions", relatedSession);
        }
    }
    /// <summary>
    /// There are no comments for Shared.Model.Schedule in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("ScheduleOfEvents")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Schedule : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Schedule object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Schedule CreateSchedule(string ID)
        {
            Schedule schedule = new Schedule();
            schedule.Id = ID;
            return schedule;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Id;
        partial void OnIdChanging(string value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Error in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Error
        {
            get
            {
                return this._Error;
            }
            set
            {
                this.OnErrorChanging(value);
                this._Error = value;
                this.OnErrorChanged();
                this.OnPropertyChanged("Error");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Error;
        partial void OnErrorChanging(string value);
        partial void OnErrorChanged();
        /// <summary>
        /// There are no comments for Tracks in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Track> Tracks
        {
            get
            {
                return this._Tracks;
            }
            set
            {
                this._Tracks = value;
                this.OnPropertyChanged("Tracks");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Track> _Tracks = new global::System.Data.Services.Client.DataServiceCollection<Track>(null, System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for TimeSlots in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<TimeSlot> TimeSlots
        {
            get
            {
                return this._TimeSlots;
            }
            set
            {
                this._TimeSlots = value;
                this.OnPropertyChanged("TimeSlots");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<TimeSlot> _TimeSlots = new global::System.Data.Services.Client.DataServiceCollection<TimeSlot>(null, System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for Speakers in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Speaker> Speakers
        {
            get
            {
                return this._Speakers;
            }
            set
            {
                this._Speakers = value;
                this.OnPropertyChanged("Speakers");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Speaker> _Speakers = new global::System.Data.Services.Client.DataServiceCollection<Speaker>(null, System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for Sessions in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Session> Sessions
        {
            get
            {
                return this._Sessions;
            }
            set
            {
                this._Sessions = value;
                this.OnPropertyChanged("Sessions");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Session> _Sessions = new global::System.Data.Services.Client.DataServiceCollection<Session>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Shared.Model.Session in the schema.
    /// </summary>
    /// <KeyProperties>
    /// SessionId
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Sessions")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("SessionId")]
    public partial class Session : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Session object.
        /// </summary>
        /// <param name="sessionId">Initial value of SessionId.</param>
        /// <param name="timeSlotId">Initial value of TimeSlotId.</param>
        /// <param name="startTime">Initial value of StartTime.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Session CreateSession(global::System.Guid sessionId, global::System.Guid timeSlotId, int startTime)
        {
            Session session = new Session();
            session.SessionId = sessionId;
            session.TimeSlotId = timeSlotId;
            session.StartTime = startTime;
            return session;
        }
        /// <summary>
        /// There are no comments for Property SessionState in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SessionState
        {
            get
            {
                return this._SessionState;
            }
            set
            {
                this.OnSessionStateChanging(value);
                this._SessionState = value;
                this.OnSessionStateChanged();
                this.OnPropertyChanged("SessionState");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SessionState;
        partial void OnSessionStateChanging(string value);
        partial void OnSessionStateChanged();
        /// <summary>
        /// There are no comments for Property Tags in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Tags
        {
            get
            {
                return this._Tags;
            }
            set
            {
                this.OnTagsChanging(value);
                this._Tags = value;
                this.OnTagsChanged();
                this.OnPropertyChanged("Tags");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Tags;
        partial void OnTagsChanging(string value);
        partial void OnTagsChanged();
        /// <summary>
        /// There are no comments for Property SessionId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid SessionId
        {
            get
            {
                return this._SessionId;
            }
            set
            {
                this.OnSessionIdChanging(value);
                this._SessionId = value;
                this.OnSessionIdChanged();
                this.OnPropertyChanged("SessionId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _SessionId;
        partial void OnSessionIdChanging(global::System.Guid value);
        partial void OnSessionIdChanged();
        /// <summary>
        /// There are no comments for Property TrackId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string TrackId
        {
            get
            {
                return this._TrackId;
            }
            set
            {
                this.OnTrackIdChanging(value);
                this._TrackId = value;
                this.OnTrackIdChanged();
                this.OnPropertyChanged("TrackId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _TrackId;
        partial void OnTrackIdChanging(string value);
        partial void OnTrackIdChanged();
        /// <summary>
        /// There are no comments for Property TimeSlotId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid TimeSlotId
        {
            get
            {
                return this._TimeSlotId;
            }
            set
            {
                this.OnTimeSlotIdChanging(value);
                this._TimeSlotId = value;
                this.OnTimeSlotIdChanged();
                this.OnPropertyChanged("TimeSlotId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _TimeSlotId;
        partial void OnTimeSlotIdChanging(global::System.Guid value);
        partial void OnTimeSlotIdChanged();
        /// <summary>
        /// There are no comments for Property Code in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Code
        {
            get
            {
                return this._Code;
            }
            set
            {
                this.OnCodeChanging(value);
                this._Code = value;
                this.OnCodeChanged();
                this.OnPropertyChanged("Code");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Code;
        partial void OnCodeChanging(string value);
        partial void OnCodeChanged();
        /// <summary>
        /// There are no comments for Property TwitterHashtag in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string TwitterHashtag
        {
            get
            {
                return this._TwitterHashtag;
            }
            set
            {
                this.OnTwitterHashtagChanging(value);
                this._TwitterHashtag = value;
                this.OnTwitterHashtagChanged();
                this.OnPropertyChanged("TwitterHashtag");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _TwitterHashtag;
        partial void OnTwitterHashtagChanging(string value);
        partial void OnTwitterHashtagChanged();
        /// <summary>
        /// There are no comments for Property ThumbnailUrl in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ThumbnailUrl
        {
            get
            {
                return this._ThumbnailUrl;
            }
            set
            {
                this.OnThumbnailUrlChanging(value);
                this._ThumbnailUrl = value;
                this.OnThumbnailUrlChanged();
                this.OnPropertyChanged("ThumbnailUrl");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ThumbnailUrl;
        partial void OnThumbnailUrlChanging(string value);
        partial void OnThumbnailUrlChanged();
        /// <summary>
        /// There are no comments for Property ShortUrl in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ShortUrl
        {
            get
            {
                return this._ShortUrl;
            }
            set
            {
                this.OnShortUrlChanging(value);
                this._ShortUrl = value;
                this.OnShortUrlChanged();
                this.OnPropertyChanged("ShortUrl");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ShortUrl;
        partial void OnShortUrlChanging(string value);
        partial void OnShortUrlChanged();
        /// <summary>
        /// There are no comments for Property Room in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Room
        {
            get
            {
                return this._Room;
            }
            set
            {
                this.OnRoomChanging(value);
                this._Room = value;
                this.OnRoomChanged();
                this.OnPropertyChanged("Room");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Room;
        partial void OnRoomChanging(string value);
        partial void OnRoomChanged();
        /// <summary>
        /// There are no comments for Property StartTime in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int StartTime
        {
            get
            {
                return this._StartTime;
            }
            set
            {
                this.OnStartTimeChanging(value);
                this._StartTime = value;
                this.OnStartTimeChanged();
                this.OnPropertyChanged("StartTime");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _StartTime;
        partial void OnStartTimeChanging(int value);
        partial void OnStartTimeChanged();
        /// <summary>
        /// There are no comments for Property ShortTitle in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ShortTitle
        {
            get
            {
                return this._ShortTitle;
            }
            set
            {
                this.OnShortTitleChanging(value);
                this._ShortTitle = value;
                this.OnShortTitleChanged();
                this.OnPropertyChanged("ShortTitle");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ShortTitle;
        partial void OnShortTitleChanging(string value);
        partial void OnShortTitleChanged();
        /// <summary>
        /// There are no comments for Property ShortDescription in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ShortDescription
        {
            get
            {
                return this._ShortDescription;
            }
            set
            {
                this.OnShortDescriptionChanging(value);
                this._ShortDescription = value;
                this.OnShortDescriptionChanged();
                this.OnPropertyChanged("ShortDescription");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ShortDescription;
        partial void OnShortDescriptionChanging(string value);
        partial void OnShortDescriptionChanged();
        /// <summary>
        /// There are no comments for Property FullTitle in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FullTitle
        {
            get
            {
                return this._FullTitle;
            }
            set
            {
                this.OnFullTitleChanging(value);
                this._FullTitle = value;
                this.OnFullTitleChanged();
                this.OnPropertyChanged("FullTitle");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FullTitle;
        partial void OnFullTitleChanging(string value);
        partial void OnFullTitleChanged();
        /// <summary>
        /// There are no comments for Property FullDescription in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FullDescription
        {
            get
            {
                return this._FullDescription;
            }
            set
            {
                this.OnFullDescriptionChanging(value);
                this._FullDescription = value;
                this.OnFullDescriptionChanged();
                this.OnPropertyChanged("FullDescription");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FullDescription;
        partial void OnFullDescriptionChanging(string value);
        partial void OnFullDescriptionChanged();
        /// <summary>
        /// There are no comments for Manifests in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Manifest> Manifests
        {
            get
            {
                return this._Manifests;
            }
            set
            {
                this._Manifests = value;
                this.OnPropertyChanged("Manifests");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Manifest> _Manifests = new global::System.Data.Services.Client.DataServiceCollection<Manifest>(null, System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for Presenters in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Presenter> Presenters
        {
            get
            {
                return this._Presenters;
            }
            set
            {
                this._Presenters = value;
                this.OnPropertyChanged("Presenters");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Presenter> _Presenters = new global::System.Data.Services.Client.DataServiceCollection<Presenter>(null, System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for DownloadableContent in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Content> DownloadableContent
        {
            get
            {
                return this._DownloadableContent;
            }
            set
            {
                this._DownloadableContent = value;
                this.OnPropertyChanged("DownloadableContent");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Content> _DownloadableContent = new global::System.Data.Services.Client.DataServiceCollection<Content>(null, System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for BackgroundMaterials in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Content> BackgroundMaterials
        {
            get
            {
                return this._BackgroundMaterials;
            }
            set
            {
                this._BackgroundMaterials = value;
                this.OnPropertyChanged("BackgroundMaterials");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Content> _BackgroundMaterials = new global::System.Data.Services.Client.DataServiceCollection<Content>(null, System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for RelatedSessions in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<RelatedSession> RelatedSessions
        {
            get
            {
                return this._RelatedSessions;
            }
            set
            {
                this._RelatedSessions = value;
                this.OnPropertyChanged("RelatedSessions");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<RelatedSession> _RelatedSessions = new global::System.Data.Services.Client.DataServiceCollection<RelatedSession>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Shared.Model.Track in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Name
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Tracks")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Name")]
    public partial class Track : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Track object.
        /// </summary>
        /// <param name="name">Initial value of Name.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Track CreateTrack(string name)
        {
            Track track = new Track();
            track.Name = name;
            return track;
        }
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
                this.OnPropertyChanged("Title");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Shared.Model.TimeSlot in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("TimeSlots")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class TimeSlot : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new TimeSlot object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="start">Initial value of Start.</param>
        /// <param name="end">Initial value of End.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static TimeSlot CreateTimeSlot(global::System.Guid ID, global::System.DateTime start, global::System.DateTime end)
        {
            TimeSlot timeSlot = new TimeSlot();
            timeSlot.Id = ID;
            timeSlot.Start = start;
            timeSlot.End = end;
            return timeSlot;
        }
        /// <summary>
        /// There are no comments for Property Duration in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Duration
        {
            get
            {
                return this._Duration;
            }
            set
            {
                this.OnDurationChanging(value);
                this._Duration = value;
                this.OnDurationChanged();
                this.OnPropertyChanged("Duration");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Duration;
        partial void OnDurationChanging(string value);
        partial void OnDurationChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Start in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Start
        {
            get
            {
                return this._Start;
            }
            set
            {
                this.OnStartChanging(value);
                this._Start = value;
                this.OnStartChanged();
                this.OnPropertyChanged("Start");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Start;
        partial void OnStartChanging(global::System.DateTime value);
        partial void OnStartChanged();
        /// <summary>
        /// There are no comments for Property StartString in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string StartString
        {
            get
            {
                return this._StartString;
            }
            set
            {
                this.OnStartStringChanging(value);
                this._StartString = value;
                this.OnStartStringChanged();
                this.OnPropertyChanged("StartString");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _StartString;
        partial void OnStartStringChanging(string value);
        partial void OnStartStringChanged();
        /// <summary>
        /// There are no comments for Property End in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime End
        {
            get
            {
                return this._End;
            }
            set
            {
                this.OnEndChanging(value);
                this._End = value;
                this.OnEndChanged();
                this.OnPropertyChanged("End");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _End;
        partial void OnEndChanging(global::System.DateTime value);
        partial void OnEndChanged();
        /// <summary>
        /// There are no comments for Property EndString in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string EndString
        {
            get
            {
                return this._EndString;
            }
            set
            {
                this.OnEndStringChanging(value);
                this._EndString = value;
                this.OnEndStringChanged();
                this.OnPropertyChanged("EndString");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _EndString;
        partial void OnEndStringChanging(string value);
        partial void OnEndStringChanged();
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Shared.Model.Speaker in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Speakers")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Speaker : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Speaker object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Speaker CreateSpeaker(global::System.Guid ID)
        {
            Speaker speaker = new Speaker();
            speaker.Id = ID;
            return speaker;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property FullName in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FullName
        {
            get
            {
                return this._FullName;
            }
            set
            {
                this.OnFullNameChanging(value);
                this._FullName = value;
                this.OnFullNameChanged();
                this.OnPropertyChanged("FullName");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FullName;
        partial void OnFullNameChanging(string value);
        partial void OnFullNameChanged();
        /// <summary>
        /// There are no comments for Property PhotoUrl in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PhotoUrl
        {
            get
            {
                return this._PhotoUrl;
            }
            set
            {
                this.OnPhotoUrlChanging(value);
                this._PhotoUrl = value;
                this.OnPhotoUrlChanged();
                this.OnPropertyChanged("PhotoUrl");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PhotoUrl;
        partial void OnPhotoUrlChanging(string value);
        partial void OnPhotoUrlChanged();
        /// <summary>
        /// There are no comments for Property Bio in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Bio
        {
            get
            {
                return this._Bio;
            }
            set
            {
                this.OnBioChanging(value);
                this._Bio = value;
                this.OnBioChanged();
                this.OnPropertyChanged("Bio");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Bio;
        partial void OnBioChanging(string value);
        partial void OnBioChanged();
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Shared.Model.Manifest in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Manifests")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Manifest : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Manifest object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Manifest CreateManifest(string ID)
        {
            Manifest manifest = new Manifest();
            manifest.Id = ID;
            return manifest;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Id;
        partial void OnIdChanging(string value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Format in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Format
        {
            get
            {
                return this._Format;
            }
            set
            {
                this.OnFormatChanging(value);
                this._Format = value;
                this.OnFormatChanged();
                this.OnPropertyChanged("Format");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Format;
        partial void OnFormatChanging(string value);
        partial void OnFormatChanged();
        /// <summary>
        /// There are no comments for Property Url in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Url
        {
            get
            {
                return this._Url;
            }
            set
            {
                this.OnUrlChanging(value);
                this._Url = value;
                this.OnUrlChanged();
                this.OnPropertyChanged("Url");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Url;
        partial void OnUrlChanging(string value);
        partial void OnUrlChanged();
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Shared.Model.Presenter in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Presenters")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Presenter : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Presenter object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Presenter CreatePresenter(global::System.Guid ID)
        {
            Presenter presenter = new Presenter();
            presenter.Id = ID;
            return presenter;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Shared.Model.Content in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Contents")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Content : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Content object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Content CreateContent(string ID)
        {
            Content content = new Content();
            content.Id = ID;
            return content;
        }
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
                this.OnPropertyChanged("Title");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Id;
        partial void OnIdChanging(string value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Url in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Url
        {
            get
            {
                return this._Url;
            }
            set
            {
                this.OnUrlChanging(value);
                this._Url = value;
                this.OnUrlChanged();
                this.OnPropertyChanged("Url");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Url;
        partial void OnUrlChanging(string value);
        partial void OnUrlChanged();
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Shared.Model.RelatedSession in the schema.
    /// </summary>
    /// <KeyProperties>
    /// SessionId
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("RelatedSessions")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("SessionId")]
    public partial class RelatedSession : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new RelatedSession object.
        /// </summary>
        /// <param name="sessionId">Initial value of SessionId.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static RelatedSession CreateRelatedSession(global::System.Guid sessionId)
        {
            RelatedSession relatedSession = new RelatedSession();
            relatedSession.SessionId = sessionId;
            return relatedSession;
        }
        /// <summary>
        /// There are no comments for Property SessionId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid SessionId
        {
            get
            {
                return this._SessionId;
            }
            set
            {
                this.OnSessionIdChanging(value);
                this._SessionId = value;
                this.OnSessionIdChanged();
                this.OnPropertyChanged("SessionId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _SessionId;
        partial void OnSessionIdChanging(global::System.Guid value);
        partial void OnSessionIdChanged();
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
